//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageSale.YardSaleServiceRefrence {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class userWCF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string pic_urlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pic_url {
            get {
                return this.pic_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.pic_urlField, value) != true)) {
                    this.pic_urlField = value;
                    this.RaisePropertyChanged("pic_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commentWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class commentWCF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commentField;
        
        private System.DateTime date_addedField;
        
        private int idField;
        
        private int item_idField;
        
        private string user_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added {
            get {
                return this.date_addedField;
            }
            set {
                if ((this.date_addedField.Equals(value) != true)) {
                    this.date_addedField = value;
                    this.RaisePropertyChanged("date_added");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.user_idField, value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="itemWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class itemWCF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime date_addedField;
        
        private string descriptionField;
        
        private int idField;
        
        private string nameField;
        
        private string owner_idField;
        
        private string pic_urlField;
        
        private float priceField;
        
        private float qualityField;
        
        private bool soldField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added {
            get {
                return this.date_addedField;
            }
            set {
                if ((this.date_addedField.Equals(value) != true)) {
                    this.date_addedField = value;
                    this.RaisePropertyChanged("date_added");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner_id {
            get {
                return this.owner_idField;
            }
            set {
                if ((object.ReferenceEquals(this.owner_idField, value) != true)) {
                    this.owner_idField = value;
                    this.RaisePropertyChanged("owner_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pic_url {
            get {
                return this.pic_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.pic_urlField, value) != true)) {
                    this.pic_urlField = value;
                    this.RaisePropertyChanged("pic_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float quality {
            get {
                return this.qualityField;
            }
            set {
                if ((this.qualityField.Equals(value) != true)) {
                    this.qualityField = value;
                    this.RaisePropertyChanged("quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sold {
            get {
                return this.soldField;
            }
            set {
                if ((this.soldField.Equals(value) != true)) {
                    this.soldField = value;
                    this.RaisePropertyChanged("sold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YardSaleServiceRefrence.IYardSale")]
    public interface IYardSale {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/createUser", ReplyAction="http://tempuri.org/IYardSale/createUserResponse")]
        System.IAsyncResult BegincreateUser(GarageSale.YardSaleServiceRefrence.userWCF user, System.AsyncCallback callback, object asyncState);
        
        bool EndcreateUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/updateUserActivity", ReplyAction="http://tempuri.org/IYardSale/updateUserActivityResponse")]
        System.IAsyncResult BeginupdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState);
        
        bool EndupdateUserActivity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/addComment", ReplyAction="http://tempuri.org/IYardSale/addCommentResponse")]
        System.IAsyncResult BeginaddComment(GarageSale.YardSaleServiceRefrence.commentWCF comment, System.AsyncCallback callback, object asyncState);
        
        bool EndaddComment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/addItem", ReplyAction="http://tempuri.org/IYardSale/addItemResponse")]
        System.IAsyncResult BeginaddItem(GarageSale.YardSaleServiceRefrence.itemWCF item, System.AsyncCallback callback, object asyncState);
        
        bool EndaddItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/getAllItems", ReplyAction="http://tempuri.org/IYardSale/getAllItemsResponse")]
        System.IAsyncResult BegingetAllItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> EndgetAllItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IYardSaleChannel : GarageSale.YardSaleServiceRefrence.IYardSale, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateUserActivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateUserActivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YardSaleClient : System.ServiceModel.ClientBase<GarageSale.YardSaleServiceRefrence.IYardSale>, GarageSale.YardSaleServiceRefrence.IYardSale {
        
        private BeginOperationDelegate onBegincreateUserDelegate;
        
        private EndOperationDelegate onEndcreateUserDelegate;
        
        private System.Threading.SendOrPostCallback oncreateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateUserActivityDelegate;
        
        private EndOperationDelegate onEndupdateUserActivityDelegate;
        
        private System.Threading.SendOrPostCallback onupdateUserActivityCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddCommentDelegate;
        
        private EndOperationDelegate onEndaddCommentDelegate;
        
        private System.Threading.SendOrPostCallback onaddCommentCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddItemDelegate;
        
        private EndOperationDelegate onEndaddItemDelegate;
        
        private System.Threading.SendOrPostCallback onaddItemCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllItemsDelegate;
        
        private EndOperationDelegate onEndgetAllItemsDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public YardSaleClient() : 
                base(YardSaleClient.GetDefaultBinding(), YardSaleClient.GetDefaultEndpointAddress()) {
        }
        
        public YardSaleClient(EndpointConfiguration endpointConfiguration) : 
                base(YardSaleClient.GetBindingForEndpoint(endpointConfiguration), YardSaleClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public YardSaleClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(YardSaleClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public YardSaleClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(YardSaleClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public YardSaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<createUserCompletedEventArgs> createUserCompleted;
        
        public event System.EventHandler<updateUserActivityCompletedEventArgs> updateUserActivityCompleted;
        
        public event System.EventHandler<addCommentCompletedEventArgs> addCommentCompleted;
        
        public event System.EventHandler<addItemCompletedEventArgs> addItemCompleted;
        
        public event System.EventHandler<getAllItemsCompletedEventArgs> getAllItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GarageSale.YardSaleServiceRefrence.IYardSale.BegincreateUser(GarageSale.YardSaleServiceRefrence.userWCF user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool GarageSale.YardSaleServiceRefrence.IYardSale.EndcreateUser(System.IAsyncResult result) {
            return base.Channel.EndcreateUser(result);
        }
        
        private System.IAsyncResult OnBegincreateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GarageSale.YardSaleServiceRefrence.userWCF user = ((GarageSale.YardSaleServiceRefrence.userWCF)(inValues[0]));
            return ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).BegincreateUser(user, callback, asyncState);
        }
        
        private object[] OnEndcreateUser(System.IAsyncResult result) {
            bool retVal = ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).EndcreateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateUserCompleted(object state) {
            if ((this.createUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createUserCompleted(this, new createUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createUserAsync(GarageSale.YardSaleServiceRefrence.userWCF user) {
            this.createUserAsync(user, null);
        }
        
        public void createUserAsync(GarageSale.YardSaleServiceRefrence.userWCF user, object userState) {
            if ((this.onBegincreateUserDelegate == null)) {
                this.onBegincreateUserDelegate = new BeginOperationDelegate(this.OnBegincreateUser);
            }
            if ((this.onEndcreateUserDelegate == null)) {
                this.onEndcreateUserDelegate = new EndOperationDelegate(this.OnEndcreateUser);
            }
            if ((this.oncreateUserCompletedDelegate == null)) {
                this.oncreateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateUserCompleted);
            }
            base.InvokeAsync(this.onBegincreateUserDelegate, new object[] {
                        user}, this.onEndcreateUserDelegate, this.oncreateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GarageSale.YardSaleServiceRefrence.IYardSale.BeginupdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateUserActivity(user_id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool GarageSale.YardSaleServiceRefrence.IYardSale.EndupdateUserActivity(System.IAsyncResult result) {
            return base.Channel.EndupdateUserActivity(result);
        }
        
        private System.IAsyncResult OnBeginupdateUserActivity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user_id = ((string)(inValues[0]));
            return ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).BeginupdateUserActivity(user_id, callback, asyncState);
        }
        
        private object[] OnEndupdateUserActivity(System.IAsyncResult result) {
            bool retVal = ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).EndupdateUserActivity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateUserActivityCompleted(object state) {
            if ((this.updateUserActivityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateUserActivityCompleted(this, new updateUserActivityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateUserActivityAsync(string user_id) {
            this.updateUserActivityAsync(user_id, null);
        }
        
        public void updateUserActivityAsync(string user_id, object userState) {
            if ((this.onBeginupdateUserActivityDelegate == null)) {
                this.onBeginupdateUserActivityDelegate = new BeginOperationDelegate(this.OnBeginupdateUserActivity);
            }
            if ((this.onEndupdateUserActivityDelegate == null)) {
                this.onEndupdateUserActivityDelegate = new EndOperationDelegate(this.OnEndupdateUserActivity);
            }
            if ((this.onupdateUserActivityCompletedDelegate == null)) {
                this.onupdateUserActivityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateUserActivityCompleted);
            }
            base.InvokeAsync(this.onBeginupdateUserActivityDelegate, new object[] {
                        user_id}, this.onEndupdateUserActivityDelegate, this.onupdateUserActivityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GarageSale.YardSaleServiceRefrence.IYardSale.BeginaddComment(GarageSale.YardSaleServiceRefrence.commentWCF comment, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddComment(comment, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool GarageSale.YardSaleServiceRefrence.IYardSale.EndaddComment(System.IAsyncResult result) {
            return base.Channel.EndaddComment(result);
        }
        
        private System.IAsyncResult OnBeginaddComment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GarageSale.YardSaleServiceRefrence.commentWCF comment = ((GarageSale.YardSaleServiceRefrence.commentWCF)(inValues[0]));
            return ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).BeginaddComment(comment, callback, asyncState);
        }
        
        private object[] OnEndaddComment(System.IAsyncResult result) {
            bool retVal = ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).EndaddComment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddCommentCompleted(object state) {
            if ((this.addCommentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addCommentCompleted(this, new addCommentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addCommentAsync(GarageSale.YardSaleServiceRefrence.commentWCF comment) {
            this.addCommentAsync(comment, null);
        }
        
        public void addCommentAsync(GarageSale.YardSaleServiceRefrence.commentWCF comment, object userState) {
            if ((this.onBeginaddCommentDelegate == null)) {
                this.onBeginaddCommentDelegate = new BeginOperationDelegate(this.OnBeginaddComment);
            }
            if ((this.onEndaddCommentDelegate == null)) {
                this.onEndaddCommentDelegate = new EndOperationDelegate(this.OnEndaddComment);
            }
            if ((this.onaddCommentCompletedDelegate == null)) {
                this.onaddCommentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddCommentCompleted);
            }
            base.InvokeAsync(this.onBeginaddCommentDelegate, new object[] {
                        comment}, this.onEndaddCommentDelegate, this.onaddCommentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GarageSale.YardSaleServiceRefrence.IYardSale.BeginaddItem(GarageSale.YardSaleServiceRefrence.itemWCF item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddItem(item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool GarageSale.YardSaleServiceRefrence.IYardSale.EndaddItem(System.IAsyncResult result) {
            return base.Channel.EndaddItem(result);
        }
        
        private System.IAsyncResult OnBeginaddItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            GarageSale.YardSaleServiceRefrence.itemWCF item = ((GarageSale.YardSaleServiceRefrence.itemWCF)(inValues[0]));
            return ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).BeginaddItem(item, callback, asyncState);
        }
        
        private object[] OnEndaddItem(System.IAsyncResult result) {
            bool retVal = ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).EndaddItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddItemCompleted(object state) {
            if ((this.addItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addItemCompleted(this, new addItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addItemAsync(GarageSale.YardSaleServiceRefrence.itemWCF item) {
            this.addItemAsync(item, null);
        }
        
        public void addItemAsync(GarageSale.YardSaleServiceRefrence.itemWCF item, object userState) {
            if ((this.onBeginaddItemDelegate == null)) {
                this.onBeginaddItemDelegate = new BeginOperationDelegate(this.OnBeginaddItem);
            }
            if ((this.onEndaddItemDelegate == null)) {
                this.onEndaddItemDelegate = new EndOperationDelegate(this.OnEndaddItem);
            }
            if ((this.onaddItemCompletedDelegate == null)) {
                this.onaddItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddItemCompleted);
            }
            base.InvokeAsync(this.onBeginaddItemDelegate, new object[] {
                        item}, this.onEndaddItemDelegate, this.onaddItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GarageSale.YardSaleServiceRefrence.IYardSale.BegingetAllItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAllItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> GarageSale.YardSaleServiceRefrence.IYardSale.EndgetAllItems(System.IAsyncResult result) {
            return base.Channel.EndgetAllItems(result);
        }
        
        private System.IAsyncResult OnBegingetAllItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).BegingetAllItems(callback, asyncState);
        }
        
        private object[] OnEndgetAllItems(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> retVal = ((GarageSale.YardSaleServiceRefrence.IYardSale)(this)).EndgetAllItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllItemsCompleted(object state) {
            if ((this.getAllItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllItemsCompleted(this, new getAllItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllItemsAsync() {
            this.getAllItemsAsync(null);
        }
        
        public void getAllItemsAsync(object userState) {
            if ((this.onBegingetAllItemsDelegate == null)) {
                this.onBegingetAllItemsDelegate = new BeginOperationDelegate(this.OnBegingetAllItems);
            }
            if ((this.onEndgetAllItemsDelegate == null)) {
                this.onEndgetAllItemsDelegate = new EndOperationDelegate(this.OnEndgetAllItems);
            }
            if ((this.ongetAllItemsCompletedDelegate == null)) {
                this.ongetAllItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllItemsCompleted);
            }
            base.InvokeAsync(this.onBegingetAllItemsDelegate, null, this.onEndgetAllItemsDelegate, this.ongetAllItemsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GarageSale.YardSaleServiceRefrence.IYardSale CreateChannel() {
            return new YardSaleClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IYardSale)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IYardSale)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:9617/YardSaleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return YardSaleClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IYardSale);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return YardSaleClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IYardSale);
        }
        
        private class YardSaleClientChannel : ChannelBase<GarageSale.YardSaleServiceRefrence.IYardSale>, GarageSale.YardSaleServiceRefrence.IYardSale {
            
            public YardSaleClientChannel(System.ServiceModel.ClientBase<GarageSale.YardSaleServiceRefrence.IYardSale> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegincreateUser(GarageSale.YardSaleServiceRefrence.userWCF user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("createUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndcreateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("createUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginupdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user_id;
                System.IAsyncResult _result = base.BeginInvoke("updateUserActivity", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndupdateUserActivity(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("updateUserActivity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddComment(GarageSale.YardSaleServiceRefrence.commentWCF comment, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = comment;
                System.IAsyncResult _result = base.BeginInvoke("addComment", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndaddComment(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("addComment", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddItem(GarageSale.YardSaleServiceRefrence.itemWCF item, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = item;
                System.IAsyncResult _result = base.BeginInvoke("addItem", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndaddItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("addItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAllItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getAllItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> EndgetAllItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF> _result = ((System.Collections.ObjectModel.ObservableCollection<GarageSale.YardSaleServiceRefrence.itemWCF>)(base.EndInvoke("getAllItems", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IYardSale,
        }
    }
}
