//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yardSaleWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class userWCF : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idField;
        
        private string nameField;
        
        private string pic_urlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pic_url
        {
            get
            {
                return this.pic_urlField;
            }
            set
            {
                this.pic_urlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commentWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class commentWCF : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string commentField;
        
        private System.DateTime date_addedField;
        
        private int idField;
        
        private int item_idField;
        
        private string user_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added
        {
            get
            {
                return this.date_addedField;
            }
            set
            {
                this.date_addedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id
        {
            get
            {
                return this.item_idField;
            }
            set
            {
                this.item_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_id
        {
            get
            {
                return this.user_idField;
            }
            set
            {
                this.user_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="itemWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class itemWCF : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime date_addedField;
        
        private string descriptionField;
        
        private int idField;
        
        private string nameField;
        
        private string owner_idField;
        
        private string pic_urlField;
        
        private float priceField;
        
        private float qualityField;
        
        private bool soldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added
        {
            get
            {
                return this.date_addedField;
            }
            set
            {
                this.date_addedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner_id
        {
            get
            {
                return this.owner_idField;
            }
            set
            {
                this.owner_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pic_url
        {
            get
            {
                return this.pic_urlField;
            }
            set
            {
                this.pic_urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                this.qualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sold
        {
            get
            {
                return this.soldField;
            }
            set
            {
                this.soldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bidWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class bidWCF : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float amountField;
        
        private string bidder_idField;
        
        private int idField;
        
        private int item_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bidder_id
        {
            get
            {
                return this.bidder_idField;
            }
            set
            {
                this.bidder_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id
        {
            get
            {
                return this.item_idField;
            }
            set
            {
                this.item_idField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IYardSale")]
public interface IYardSale
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/CreateUser", ReplyAction="http://tempuri.org/IYardSale/CreateUserResponse")]
    bool CreateUser(yardSaleWCF.userWCF user);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/CreateUser", ReplyAction="http://tempuri.org/IYardSale/CreateUserResponse")]
    System.IAsyncResult BeginCreateUser(yardSaleWCF.userWCF user, System.AsyncCallback callback, object asyncState);
    
    bool EndCreateUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/UpdateUserActivity", ReplyAction="http://tempuri.org/IYardSale/UpdateUserActivityResponse")]
    bool UpdateUserActivity(string user_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/UpdateUserActivity", ReplyAction="http://tempuri.org/IYardSale/UpdateUserActivityResponse")]
    System.IAsyncResult BeginUpdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdateUserActivity(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddComment", ReplyAction="http://tempuri.org/IYardSale/AddCommentResponse")]
    bool AddComment(yardSaleWCF.commentWCF comment);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddComment", ReplyAction="http://tempuri.org/IYardSale/AddCommentResponse")]
    System.IAsyncResult BeginAddComment(yardSaleWCF.commentWCF comment, System.AsyncCallback callback, object asyncState);
    
    bool EndAddComment(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddItem", ReplyAction="http://tempuri.org/IYardSale/AddItemResponse")]
    bool AddItem(yardSaleWCF.itemWCF item);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddItem", ReplyAction="http://tempuri.org/IYardSale/AddItemResponse")]
    System.IAsyncResult BeginAddItem(yardSaleWCF.itemWCF item, System.AsyncCallback callback, object asyncState);
    
    bool EndAddItem(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddBid", ReplyAction="http://tempuri.org/IYardSale/AddBidResponse")]
    bool AddBid(yardSaleWCF.bidWCF bid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddBid", ReplyAction="http://tempuri.org/IYardSale/AddBidResponse")]
    System.IAsyncResult BeginAddBid(yardSaleWCF.bidWCF bid, System.AsyncCallback callback, object asyncState);
    
    bool EndAddBid(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetTopBid", ReplyAction="http://tempuri.org/IYardSale/GetTopBidResponse")]
    yardSaleWCF.bidWCF GetTopBid(int item_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetTopBid", ReplyAction="http://tempuri.org/IYardSale/GetTopBidResponse")]
    System.IAsyncResult BeginGetTopBid(int item_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.bidWCF EndGetTopBid(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetAllItems", ReplyAction="http://tempuri.org/IYardSale/GetAllItemsResponse")]
    yardSaleWCF.itemWCF[] GetAllItems();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetAllItems", ReplyAction="http://tempuri.org/IYardSale/GetAllItemsResponse")]
    System.IAsyncResult BeginGetAllItems(System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.itemWCF[] EndGetAllItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetUser", ReplyAction="http://tempuri.org/IYardSale/GetUserResponse")]
    yardSaleWCF.userWCF GetUser(string id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetUser", ReplyAction="http://tempuri.org/IYardSale/GetUserResponse")]
    System.IAsyncResult BeginGetUser(string id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.userWCF EndGetUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetComments", ReplyAction="http://tempuri.org/IYardSale/GetCommentsResponse")]
    yardSaleWCF.commentWCF[] GetComments(int item_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetComments", ReplyAction="http://tempuri.org/IYardSale/GetCommentsResponse")]
    System.IAsyncResult BeginGetComments(int item_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.commentWCF[] EndGetComments(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IYardSaleChannel : IYardSale, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class YardSaleClient : System.ServiceModel.ClientBase<IYardSale>, IYardSale
{
    
    public YardSaleClient()
    {
    }
    
    public YardSaleClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public YardSaleClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YardSaleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YardSaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool CreateUser(yardSaleWCF.userWCF user)
    {
        return base.Channel.CreateUser(user);
    }
    
    public System.IAsyncResult BeginCreateUser(yardSaleWCF.userWCF user, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCreateUser(user, callback, asyncState);
    }
    
    public bool EndCreateUser(System.IAsyncResult result)
    {
        return base.Channel.EndCreateUser(result);
    }
    
    public bool UpdateUserActivity(string user_id)
    {
        return base.Channel.UpdateUserActivity(user_id);
    }
    
    public System.IAsyncResult BeginUpdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateUserActivity(user_id, callback, asyncState);
    }
    
    public bool EndUpdateUserActivity(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateUserActivity(result);
    }
    
    public bool AddComment(yardSaleWCF.commentWCF comment)
    {
        return base.Channel.AddComment(comment);
    }
    
    public System.IAsyncResult BeginAddComment(yardSaleWCF.commentWCF comment, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddComment(comment, callback, asyncState);
    }
    
    public bool EndAddComment(System.IAsyncResult result)
    {
        return base.Channel.EndAddComment(result);
    }
    
    public bool AddItem(yardSaleWCF.itemWCF item)
    {
        return base.Channel.AddItem(item);
    }
    
    public System.IAsyncResult BeginAddItem(yardSaleWCF.itemWCF item, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddItem(item, callback, asyncState);
    }
    
    public bool EndAddItem(System.IAsyncResult result)
    {
        return base.Channel.EndAddItem(result);
    }
    
    public bool AddBid(yardSaleWCF.bidWCF bid)
    {
        return base.Channel.AddBid(bid);
    }
    
    public System.IAsyncResult BeginAddBid(yardSaleWCF.bidWCF bid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddBid(bid, callback, asyncState);
    }
    
    public bool EndAddBid(System.IAsyncResult result)
    {
        return base.Channel.EndAddBid(result);
    }
    
    public yardSaleWCF.bidWCF GetTopBid(int item_id)
    {
        return base.Channel.GetTopBid(item_id);
    }
    
    public System.IAsyncResult BeginGetTopBid(int item_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetTopBid(item_id, callback, asyncState);
    }
    
    public yardSaleWCF.bidWCF EndGetTopBid(System.IAsyncResult result)
    {
        return base.Channel.EndGetTopBid(result);
    }
    
    public yardSaleWCF.itemWCF[] GetAllItems()
    {
        return base.Channel.GetAllItems();
    }
    
    public System.IAsyncResult BeginGetAllItems(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAllItems(callback, asyncState);
    }
    
    public yardSaleWCF.itemWCF[] EndGetAllItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetAllItems(result);
    }
    
    public yardSaleWCF.userWCF GetUser(string id)
    {
        return base.Channel.GetUser(id);
    }
    
    public System.IAsyncResult BeginGetUser(string id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUser(id, callback, asyncState);
    }
    
    public yardSaleWCF.userWCF EndGetUser(System.IAsyncResult result)
    {
        return base.Channel.EndGetUser(result);
    }
    
    public yardSaleWCF.commentWCF[] GetComments(int item_id)
    {
        return base.Channel.GetComments(item_id);
    }
    
    public System.IAsyncResult BeginGetComments(int item_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetComments(item_id, callback, asyncState);
    }
    
    public yardSaleWCF.commentWCF[] EndGetComments(System.IAsyncResult result)
    {
        return base.Channel.EndGetComments(result);
    }
}
