//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yardSaleWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class userWCF : object, System.ComponentModel.INotifyPropertyChanged
    {
        
      
        
        private int FBLA_chapter_idField;
        
        private string emailField;
        
        private string idField;
        
        private string nameField;
        
        private string pic_urlField;
        
     
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FBLA_chapter_id
        {
            get
            {
                return this.FBLA_chapter_idField;
            }
            set
            {
                if ((this.FBLA_chapter_idField.Equals(value) != true))
                {
                    this.FBLA_chapter_idField = value;
                    this.RaisePropertyChanged("FBLA_chapter_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.emailField, value) != true))
                {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((object.ReferenceEquals(this.idField, value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.nameField, value) != true))
                {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pic_url
        {
            get
            {
                return this.pic_urlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.pic_urlField, value) != true))
                {
                    this.pic_urlField = value;
                    this.RaisePropertyChanged("pic_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="commentWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class commentWCF : object, System.ComponentModel.INotifyPropertyChanged
    {
        
      
        
        private string commentField;
        
        private System.DateTime date_addedField;
        
        private int idField;
        
        private int item_idField;
        
        private string user_idField;
        
     
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.commentField, value) != true))
                {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added
        {
            get
            {
                return this.date_addedField;
            }
            set
            {
                if ((this.date_addedField.Equals(value) != true))
                {
                    this.date_addedField = value;
                    this.RaisePropertyChanged("date_added");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id
        {
            get
            {
                return this.item_idField;
            }
            set
            {
                if ((this.item_idField.Equals(value) != true))
                {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_id
        {
            get
            {
                return this.user_idField;
            }
            set
            {
                if ((object.ReferenceEquals(this.user_idField, value) != true))
                {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="itemWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class itemWCF : object, System.ComponentModel.INotifyPropertyChanged
    {
        
      
        
        private System.DateTime date_addedField;
        
        private string descriptionField;
        
        private int idField;
        
        private string nameField;
        
        private string owner_idField;
        
        private byte[] pictureField;
        
        private float priceField;
        
        private float qualityField;
        
        private bool soldField;
        
     
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_added
        {
            get
            {
                return this.date_addedField;
            }
            set
            {
                if ((this.date_addedField.Equals(value) != true))
                {
                    this.date_addedField = value;
                    this.RaisePropertyChanged("date_added");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.descriptionField, value) != true))
                {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.nameField, value) != true))
                {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner_id
        {
            get
            {
                return this.owner_idField;
            }
            set
            {
                if ((object.ReferenceEquals(this.owner_idField, value) != true))
                {
                    this.owner_idField = value;
                    this.RaisePropertyChanged("owner_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] picture
        {
            get
            {
                return this.pictureField;
            }
            set
            {
                if ((object.ReferenceEquals(this.pictureField, value) != true))
                {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                if ((this.priceField.Equals(value) != true))
                {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                if ((this.qualityField.Equals(value) != true))
                {
                    this.qualityField = value;
                    this.RaisePropertyChanged("quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool sold
        {
            get
            {
                return this.soldField;
            }
            set
            {
                if ((this.soldField.Equals(value) != true))
                {
                    this.soldField = value;
                    this.RaisePropertyChanged("sold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bidWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class bidWCF : object, System.ComponentModel.INotifyPropertyChanged
    {
        
      
        
        private float amountField;
        
        private string bidder_idField;
        
        private int idField;
        
        private int item_idField;
        
     
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                if ((this.amountField.Equals(value) != true))
                {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bidder_id
        {
            get
            {
                return this.bidder_idField;
            }
            set
            {
                if ((object.ReferenceEquals(this.bidder_idField, value) != true))
                {
                    this.bidder_idField = value;
                    this.RaisePropertyChanged("bidder_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id
        {
            get
            {
                return this.item_idField;
            }
            set
            {
                if ((this.item_idField.Equals(value) != true))
                {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fblaChapterWCF", Namespace="http://schemas.datacontract.org/2004/07/yardSaleWCF")]
    public partial class fblaChapterWCF : object, System.ComponentModel.INotifyPropertyChanged
    {
        
      
        
        private string cityField;
        
        private string contact_emailField;
        
        private int idField;
        
        private string nameField;
        
        private string payment_emailField;
        
        private byte[] pictureField;
        
        private string schoolField;
        
        private string stateField;
        
     
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.cityField, value) != true))
                {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact_email
        {
            get
            {
                return this.contact_emailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.contact_emailField, value) != true))
                {
                    this.contact_emailField = value;
                    this.RaisePropertyChanged("contact_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField.Equals(value) != true))
                {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.nameField, value) != true))
                {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_email
        {
            get
            {
                return this.payment_emailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.payment_emailField, value) != true))
                {
                    this.payment_emailField = value;
                    this.RaisePropertyChanged("payment_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] picture
        {
            get
            {
                return this.pictureField;
            }
            set
            {
                if ((object.ReferenceEquals(this.pictureField, value) != true))
                {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string school
        {
            get
            {
                return this.schoolField;
            }
            set
            {
                if ((object.ReferenceEquals(this.schoolField, value) != true))
                {
                    this.schoolField = value;
                    this.RaisePropertyChanged("school");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.stateField, value) != true))
                {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IYardSale")]
public interface IYardSale
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/UpdateUser", ReplyAction="http://tempuri.org/IYardSale/UpdateUserResponse")]
    bool UpdateUser(yardSaleWCF.userWCF user);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/UpdateUser", ReplyAction="http://tempuri.org/IYardSale/UpdateUserResponse")]
    System.IAsyncResult BeginUpdateUser(yardSaleWCF.userWCF user, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdateUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/UpdateUserActivity", ReplyAction="http://tempuri.org/IYardSale/UpdateUserActivityResponse")]
    bool UpdateUserActivity(string user_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/UpdateUserActivity", ReplyAction="http://tempuri.org/IYardSale/UpdateUserActivityResponse")]
    System.IAsyncResult BeginUpdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdateUserActivity(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddComment", ReplyAction="http://tempuri.org/IYardSale/AddCommentResponse")]
    bool AddComment(yardSaleWCF.commentWCF comment);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddComment", ReplyAction="http://tempuri.org/IYardSale/AddCommentResponse")]
    System.IAsyncResult BeginAddComment(yardSaleWCF.commentWCF comment, System.AsyncCallback callback, object asyncState);
    
    bool EndAddComment(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddItem", ReplyAction="http://tempuri.org/IYardSale/AddItemResponse")]
    bool AddItem(yardSaleWCF.itemWCF item);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddItem", ReplyAction="http://tempuri.org/IYardSale/AddItemResponse")]
    System.IAsyncResult BeginAddItem(yardSaleWCF.itemWCF item, System.AsyncCallback callback, object asyncState);
    
    bool EndAddItem(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/AddBid", ReplyAction="http://tempuri.org/IYardSale/AddBidResponse")]
    bool AddBid(yardSaleWCF.bidWCF bid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/AddBid", ReplyAction="http://tempuri.org/IYardSale/AddBidResponse")]
    System.IAsyncResult BeginAddBid(yardSaleWCF.bidWCF bid, System.AsyncCallback callback, object asyncState);
    
    bool EndAddBid(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetTopBid", ReplyAction="http://tempuri.org/IYardSale/GetTopBidResponse")]
    yardSaleWCF.bidWCF GetTopBid(int item_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetTopBid", ReplyAction="http://tempuri.org/IYardSale/GetTopBidResponse")]
    System.IAsyncResult BeginGetTopBid(int item_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.bidWCF EndGetTopBid(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetAllItems", ReplyAction="http://tempuri.org/IYardSale/GetAllItemsResponse")]
    yardSaleWCF.itemWCF[] GetAllItems();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetAllItems", ReplyAction="http://tempuri.org/IYardSale/GetAllItemsResponse")]
    System.IAsyncResult BeginGetAllItems(System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.itemWCF[] EndGetAllItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetUser", ReplyAction="http://tempuri.org/IYardSale/GetUserResponse")]
    yardSaleWCF.userWCF GetUser(string id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetUser", ReplyAction="http://tempuri.org/IYardSale/GetUserResponse")]
    System.IAsyncResult BeginGetUser(string id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.userWCF EndGetUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetComments", ReplyAction="http://tempuri.org/IYardSale/GetCommentsResponse")]
    yardSaleWCF.commentWCF[] GetComments(int item_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetComments", ReplyAction="http://tempuri.org/IYardSale/GetCommentsResponse")]
    System.IAsyncResult BeginGetComments(int item_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.commentWCF[] EndGetComments(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/SellItem", ReplyAction="http://tempuri.org/IYardSale/SellItemResponse")]
    bool SellItem(int item_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/SellItem", ReplyAction="http://tempuri.org/IYardSale/SellItemResponse")]
    System.IAsyncResult BeginSellItem(int item_id, System.AsyncCallback callback, object asyncState);
    
    bool EndSellItem(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetSearchedItems", ReplyAction="http://tempuri.org/IYardSale/GetSearchedItemsResponse")]
    yardSaleWCF.itemWCF[] GetSearchedItems(string search);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetSearchedItems", ReplyAction="http://tempuri.org/IYardSale/GetSearchedItemsResponse")]
    System.IAsyncResult BeginGetSearchedItems(string search, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.itemWCF[] EndGetSearchedItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetSearchedUsers", ReplyAction="http://tempuri.org/IYardSale/GetSearchedUsersResponse")]
    yardSaleWCF.userWCF[] GetSearchedUsers(string search);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetSearchedUsers", ReplyAction="http://tempuri.org/IYardSale/GetSearchedUsersResponse")]
    System.IAsyncResult BeginGetSearchedUsers(string search, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.userWCF[] EndGetSearchedUsers(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetItemsAssociatedWithUser", ReplyAction="http://tempuri.org/IYardSale/GetItemsAssociatedWithUserResponse")]
    yardSaleWCF.itemWCF[] GetItemsAssociatedWithUser(string user_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetItemsAssociatedWithUser", ReplyAction="http://tempuri.org/IYardSale/GetItemsAssociatedWithUserResponse")]
    System.IAsyncResult BeginGetItemsAssociatedWithUser(string user_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.itemWCF[] EndGetItemsAssociatedWithUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetFBLAChapterItems", ReplyAction="http://tempuri.org/IYardSale/GetFBLAChapterItemsResponse")]
    yardSaleWCF.itemWCF[] GetFBLAChapterItems(int chapter_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetFBLAChapterItems", ReplyAction="http://tempuri.org/IYardSale/GetFBLAChapterItemsResponse")]
    System.IAsyncResult BeginGetFBLAChapterItems(int chapter_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.itemWCF[] EndGetFBLAChapterItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetUsersByChapterStatus", ReplyAction="http://tempuri.org/IYardSale/GetUsersByChapterStatusResponse")]
    yardSaleWCF.userWCF[] GetUsersByChapterStatus(int status, int chapter_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetUsersByChapterStatus", ReplyAction="http://tempuri.org/IYardSale/GetUsersByChapterStatusResponse")]
    System.IAsyncResult BeginGetUsersByChapterStatus(int status, int chapter_id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.userWCF[] EndGetUsersByChapterStatus(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/SetChapterStatusOfUser", ReplyAction="http://tempuri.org/IYardSale/SetChapterStatusOfUserResponse")]
    bool SetChapterStatusOfUser(int status, string user_id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/SetChapterStatusOfUser", ReplyAction="http://tempuri.org/IYardSale/SetChapterStatusOfUserResponse")]
    System.IAsyncResult BeginSetChapterStatusOfUser(int status, string user_id, System.AsyncCallback callback, object asyncState);
    
    bool EndSetChapterStatusOfUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetSearchedChapters", ReplyAction="http://tempuri.org/IYardSale/GetSearchedChaptersResponse")]
    yardSaleWCF.fblaChapterWCF[] GetSearchedChapters(string search);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetSearchedChapters", ReplyAction="http://tempuri.org/IYardSale/GetSearchedChaptersResponse")]
    System.IAsyncResult BeginGetSearchedChapters(string search, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.fblaChapterWCF[] EndGetSearchedChapters(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/GetFBLAChapter", ReplyAction="http://tempuri.org/IYardSale/GetFBLAChapterResponse")]
    yardSaleWCF.fblaChapterWCF GetFBLAChapter(int id);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/GetFBLAChapter", ReplyAction="http://tempuri.org/IYardSale/GetFBLAChapterResponse")]
    System.IAsyncResult BeginGetFBLAChapter(int id, System.AsyncCallback callback, object asyncState);
    
    yardSaleWCF.fblaChapterWCF EndGetFBLAChapter(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYardSale/SetFBLAChapterPicture", ReplyAction="http://tempuri.org/IYardSale/SetFBLAChapterPictureResponse")]
    bool SetFBLAChapterPicture(int id, byte[] picture);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IYardSale/SetFBLAChapterPicture", ReplyAction="http://tempuri.org/IYardSale/SetFBLAChapterPictureResponse")]
    System.IAsyncResult BeginSetFBLAChapterPicture(int id, byte[] picture, System.AsyncCallback callback, object asyncState);
    
    bool EndSetFBLAChapterPicture(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IYardSaleChannel : IYardSale, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class YardSaleClient : System.ServiceModel.ClientBase<IYardSale>, IYardSale
{
    
    public YardSaleClient()
    {
    }
    
    public YardSaleClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public YardSaleClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YardSaleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YardSaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool UpdateUser(yardSaleWCF.userWCF user)
    {
        return base.Channel.UpdateUser(user);
    }
    
    public System.IAsyncResult BeginUpdateUser(yardSaleWCF.userWCF user, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateUser(user, callback, asyncState);
    }
    
    public bool EndUpdateUser(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateUser(result);
    }
    
    public bool UpdateUserActivity(string user_id)
    {
        return base.Channel.UpdateUserActivity(user_id);
    }
    
    public System.IAsyncResult BeginUpdateUserActivity(string user_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateUserActivity(user_id, callback, asyncState);
    }
    
    public bool EndUpdateUserActivity(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateUserActivity(result);
    }
    
    public bool AddComment(yardSaleWCF.commentWCF comment)
    {
        return base.Channel.AddComment(comment);
    }
    
    public System.IAsyncResult BeginAddComment(yardSaleWCF.commentWCF comment, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddComment(comment, callback, asyncState);
    }
    
    public bool EndAddComment(System.IAsyncResult result)
    {
        return base.Channel.EndAddComment(result);
    }
    
    public bool AddItem(yardSaleWCF.itemWCF item)
    {
        return base.Channel.AddItem(item);
    }
    
    public System.IAsyncResult BeginAddItem(yardSaleWCF.itemWCF item, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddItem(item, callback, asyncState);
    }
    
    public bool EndAddItem(System.IAsyncResult result)
    {
        return base.Channel.EndAddItem(result);
    }
    
    public bool AddBid(yardSaleWCF.bidWCF bid)
    {
        return base.Channel.AddBid(bid);
    }
    
    public System.IAsyncResult BeginAddBid(yardSaleWCF.bidWCF bid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddBid(bid, callback, asyncState);
    }
    
    public bool EndAddBid(System.IAsyncResult result)
    {
        return base.Channel.EndAddBid(result);
    }
    
    public yardSaleWCF.bidWCF GetTopBid(int item_id)
    {
        return base.Channel.GetTopBid(item_id);
    }
    
    public System.IAsyncResult BeginGetTopBid(int item_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetTopBid(item_id, callback, asyncState);
    }
    
    public yardSaleWCF.bidWCF EndGetTopBid(System.IAsyncResult result)
    {
        return base.Channel.EndGetTopBid(result);
    }
    
    public yardSaleWCF.itemWCF[] GetAllItems()
    {
        return base.Channel.GetAllItems();
    }
    
    public System.IAsyncResult BeginGetAllItems(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAllItems(callback, asyncState);
    }
    
    public yardSaleWCF.itemWCF[] EndGetAllItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetAllItems(result);
    }
    
    public yardSaleWCF.userWCF GetUser(string id)
    {
        return base.Channel.GetUser(id);
    }
    
    public System.IAsyncResult BeginGetUser(string id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUser(id, callback, asyncState);
    }
    
    public yardSaleWCF.userWCF EndGetUser(System.IAsyncResult result)
    {
        return base.Channel.EndGetUser(result);
    }
    
    public yardSaleWCF.commentWCF[] GetComments(int item_id)
    {
        return base.Channel.GetComments(item_id);
    }
    
    public System.IAsyncResult BeginGetComments(int item_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetComments(item_id, callback, asyncState);
    }
    
    public yardSaleWCF.commentWCF[] EndGetComments(System.IAsyncResult result)
    {
        return base.Channel.EndGetComments(result);
    }
    
    public bool SellItem(int item_id)
    {
        return base.Channel.SellItem(item_id);
    }
    
    public System.IAsyncResult BeginSellItem(int item_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSellItem(item_id, callback, asyncState);
    }
    
    public bool EndSellItem(System.IAsyncResult result)
    {
        return base.Channel.EndSellItem(result);
    }
    
    public yardSaleWCF.itemWCF[] GetSearchedItems(string search)
    {
        return base.Channel.GetSearchedItems(search);
    }
    
    public System.IAsyncResult BeginGetSearchedItems(string search, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSearchedItems(search, callback, asyncState);
    }
    
    public yardSaleWCF.itemWCF[] EndGetSearchedItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetSearchedItems(result);
    }
    
    public yardSaleWCF.userWCF[] GetSearchedUsers(string search)
    {
        return base.Channel.GetSearchedUsers(search);
    }
    
    public System.IAsyncResult BeginGetSearchedUsers(string search, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSearchedUsers(search, callback, asyncState);
    }
    
    public yardSaleWCF.userWCF[] EndGetSearchedUsers(System.IAsyncResult result)
    {
        return base.Channel.EndGetSearchedUsers(result);
    }
    
    public yardSaleWCF.itemWCF[] GetItemsAssociatedWithUser(string user_id)
    {
        return base.Channel.GetItemsAssociatedWithUser(user_id);
    }
    
    public System.IAsyncResult BeginGetItemsAssociatedWithUser(string user_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetItemsAssociatedWithUser(user_id, callback, asyncState);
    }
    
    public yardSaleWCF.itemWCF[] EndGetItemsAssociatedWithUser(System.IAsyncResult result)
    {
        return base.Channel.EndGetItemsAssociatedWithUser(result);
    }
    
    public yardSaleWCF.itemWCF[] GetFBLAChapterItems(int chapter_id)
    {
        return base.Channel.GetFBLAChapterItems(chapter_id);
    }
    
    public System.IAsyncResult BeginGetFBLAChapterItems(int chapter_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetFBLAChapterItems(chapter_id, callback, asyncState);
    }
    
    public yardSaleWCF.itemWCF[] EndGetFBLAChapterItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetFBLAChapterItems(result);
    }
    
    public yardSaleWCF.userWCF[] GetUsersByChapterStatus(int status, int chapter_id)
    {
        return base.Channel.GetUsersByChapterStatus(status, chapter_id);
    }
    
    public System.IAsyncResult BeginGetUsersByChapterStatus(int status, int chapter_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUsersByChapterStatus(status, chapter_id, callback, asyncState);
    }
    
    public yardSaleWCF.userWCF[] EndGetUsersByChapterStatus(System.IAsyncResult result)
    {
        return base.Channel.EndGetUsersByChapterStatus(result);
    }
    
    public bool SetChapterStatusOfUser(int status, string user_id)
    {
        return base.Channel.SetChapterStatusOfUser(status, user_id);
    }
    
    public System.IAsyncResult BeginSetChapterStatusOfUser(int status, string user_id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSetChapterStatusOfUser(status, user_id, callback, asyncState);
    }
    
    public bool EndSetChapterStatusOfUser(System.IAsyncResult result)
    {
        return base.Channel.EndSetChapterStatusOfUser(result);
    }
    
    public yardSaleWCF.fblaChapterWCF[] GetSearchedChapters(string search)
    {
        return base.Channel.GetSearchedChapters(search);
    }
    
    public System.IAsyncResult BeginGetSearchedChapters(string search, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSearchedChapters(search, callback, asyncState);
    }
    
    public yardSaleWCF.fblaChapterWCF[] EndGetSearchedChapters(System.IAsyncResult result)
    {
        return base.Channel.EndGetSearchedChapters(result);
    }
    
    public yardSaleWCF.fblaChapterWCF GetFBLAChapter(int id)
    {
        return base.Channel.GetFBLAChapter(id);
    }
    
    public System.IAsyncResult BeginGetFBLAChapter(int id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetFBLAChapter(id, callback, asyncState);
    }
    
    public yardSaleWCF.fblaChapterWCF EndGetFBLAChapter(System.IAsyncResult result)
    {
        return base.Channel.EndGetFBLAChapter(result);
    }
    
    public bool SetFBLAChapterPicture(int id, byte[] picture)
    {
        return base.Channel.SetFBLAChapterPicture(id, picture);
    }
    
    public System.IAsyncResult BeginSetFBLAChapterPicture(int id, byte[] picture, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSetFBLAChapterPicture(id, picture, callback, asyncState);
    }
    
    public bool EndSetFBLAChapterPicture(System.IAsyncResult result)
    {
        return base.Channel.EndSetFBLAChapterPicture(result);
    }
}
